name: PR Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint

  test:
    name: Run Tests
    needs: lint
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Debug Environment
        run: |
          echo "Xcode path:"
          xcode-select -p
          echo "\nXcode version:"
          xcodebuild -version
    
      - name: Check Swift version
        run: swift --version
        
      - name: Clean DerivedData
        run: rm -rf Build/DerivedData
        
      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Run Tests with xcbeautify
        run: |
          set -o pipefail && \
          xcodebuild test \
            -project MonKiV2.xcodeproj \
            -scheme MonKiV2 \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1' \
            -derivedDataPath Build/DerivedData \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
          | xcbeautify --quiet
